### PR TITLE
Sort collected IPv4 and IPv6 addresses by network device config ID

### LINKED ISSUE #368: vsphere_virtual_machine network_interface wrong order of ip configuration
Hi there,

i have a strange ordering problem with the vsphere provider. i want to have 4 interfaces out of 4 different networks. but the specified ip for the last interface get configured on the first. After this it proceeds in order.

### Terraform Version
Terraform v0.11.1

### vSphere Provider Version
provider.vsphere v1.2.0

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "srv" {
  count            = 1
  name             = "srv${count.index + 1}.example.com"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus         = 1
  memory           = 1024
  guest_id         = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type        = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id = "${data.vsphere_network.vlan10.id}"
  }

  network_interface {
    network_id = "${data.vsphere_network.vlan20.id}"
  }

  network_interface {
    network_id = "${data.vsphere_network.vlan30.id}"
  }

  network_interface {
    network_id = "${data.vsphere_network.vlan40.id}"
  }

  disk {
    name = "srv${count.index + 1}.example.com.vmdk"
    size = "${data.vsphere_virtual_machine.template.disks.0.size}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "srv${count.index + 1}"
        domain    = "example.com"
      }

      network_interface {
        ipv4_address = "10.0.10.${count.index + 1}"
        ipv4_netmask = 24
      }

      network_interface {
        ipv4_address = "10.0.20.${count.index + 1}"
        ipv4_netmask = 24
      }

      network_interface {
        ipv4_address = "10.0.30.${count.index + 1}"
        ipv4_netmask = 24
      }

      network_interface {
        ipv4_address = "10.0.40.${count.index + 1}"
        ipv4_netmask = 24
      }

      ipv4_gateway    = "10.0.30.254"
      dns_server_list = ["8.8.8.8"]
    }
  }
}

```

### Expected Behavior
The network interfaces should be configured in the order they where declared

eth0 = 10.0.10.1
eth1 = 10.0.20.1
eth2 = 10.0.30.1
eth3 = 10.0.40.1

### Actual Behavior
The last declared interface ip is configured on the first device. after that, the order is like declared

eth0 = 10.0.40.1
eth1 = 10.0.10.1
eth2 = 10.0.20.1
eth3 = 10.0.30.1

### Schema:
last
first 
second
... n

### Workaround
Configure the desired first address as last in the customize part of the clone section.

With this i get my desired state of

eth0 = 10.0.10.1
eth1 = 10.0.20.1
eth2 = 10.0.30.1
eth3 = 10.0.40.1

### terraform show
```
clone.# = 1
clone.0.customize.# = 1
clone.0.customize.0.dns_server_list.# = 1
clone.0.customize.0.dns_server_list.0 = 8.8.8.8
clone.0.customize.0.dns_suffix_list.# = 0
clone.0.customize.0.ipv4_gateway = 10.0.30.254
clone.0.customize.0.ipv6_gateway =
clone.0.customize.0.linux_options.# = 1
clone.0.customize.0.linux_options.0.domain = example.com
clone.0.customize.0.linux_options.0.host_name = srv1
clone.0.customize.0.linux_options.0.hw_clock_utc = true
clone.0.customize.0.linux_options.0.time_zone =
clone.0.customize.0.network_interface.# = 4
clone.0.customize.0.network_interface.0.dns_domain =
clone.0.customize.0.network_interface.0.dns_server_list.# = 0
clone.0.customize.0.network_interface.0.ipv4_address = 10.0.10.1
clone.0.customize.0.network_interface.0.ipv4_netmask = 24
clone.0.customize.0.network_interface.0.ipv6_address =
clone.0.customize.0.network_interface.0.ipv6_netmask = 0
clone.0.customize.0.network_interface.1.dns_domain =
clone.0.customize.0.network_interface.1.dns_server_list.# = 0
clone.0.customize.0.network_interface.1.ipv4_address = 10.0.20.1
clone.0.customize.0.network_interface.1.ipv4_netmask = 24
clone.0.customize.0.network_interface.1.ipv6_address =
clone.0.customize.0.network_interface.1.ipv6_netmask = 0
clone.0.customize.0.network_interface.2.dns_domain =
clone.0.customize.0.network_interface.2.dns_server_list.# = 0
clone.0.customize.0.network_interface.2.ipv4_address = 10.0.30.1
clone.0.customize.0.network_interface.2.ipv4_netmask = 24
clone.0.customize.0.network_interface.2.ipv6_address =
clone.0.customize.0.network_interface.2.ipv6_netmask = 0
clone.0.customize.0.network_interface.3.dns_domain =
clone.0.customize.0.network_interface.3.dns_server_list.# = 0
clone.0.customize.0.network_interface.3.ipv4_address = 10.0.40.1
clone.0.customize.0.network_interface.3.ipv4_netmask = 24
clone.0.customize.0.network_interface.3.ipv6_address =
clone.0.customize.0.network_interface.3.ipv6_netmask = 0
clone.0.customize.0.timeout = 10
clone.0.customize.0.windows_options.# = 0
clone.0.customize.0.windows_sysprep_text =
clone.0.linked_clone = false
clone.0.template_uuid = 421a3e20-cedb-ec63-29ba-1e36fb11da87
clone.0.timeout = 30
...
uest_ip_addresses.# = 8
guest_ip_addresses.0 = 10.0.40.1
guest_ip_addresses.1 = 10.0.10.1
guest_ip_addresses.2 = 10.0.20.1
guest_ip_addresses.3 = 10.0.30.1
guest_ip_addresses.4 = fe80::250:56ff:fe9a:2d5a
guest_ip_addresses.5 = fe80::250:56ff:fe9a:6b56
guest_ip_addresses.6 = fe80::250:56ff:fe9a:6cdc
guest_ip_addresses.7 = fe80::250:56ff:fe9a:bc7b
```

### PR DESCRIPTION
**Pull request by sirlatrom**
Resolves #368 and helps ensure the order of guest IP addresses corresponds to the declared order of network interfaces. If each interface has exactly one IP address, it becomes possible to get the IP address for a specific interface, e.g. for `eth1` by using the expression `vsphere_virtual_machine.vm.guest_ip_addresses[1]`.

### CODE REVIEW

**Comment by sirlatrom** [comment]
Rebased on origin/master. @bill-rich or @aareet, any chance this will make it into v1.14.0 or even v1.13.x?

**Comment by rumstattd** [comment]
looking forward to seeing this, as network device ordering is effecting us in vsphere (Terraform v0.12.18)

**Comment by sirlatrom** [comment]
> Would it be possible to add some integration tests though?
> 
> Given that we're now making ordering of interfaces strict I think it would be nice to know in advance if future changes alter the ordering of the interfaces with potentially disastrous consequences to someone's VM builds :).

That's a good point. I don't see any tests being explicitly marked as integration tests, and there is no existing test file for virtual_machine_guest_structure.go. Should I add virtual_machine_guest_structure_test.go and attempt to test the input/output contract of the modified function?

**Comment by koikonom** [comment]
I would put the test in resource_vsphere_virtual_machine_test.go, along with the rest. There are more tests there that can give you some idea of what we're looking for.

You can find information around acceptance tests here https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html and, obviously, feel free to ask any questions that may pop up :) .

**Comment by sirlatrom** [comment]
> I would put the test in resource_vsphere_virtual_machine_test.go, along with the rest. There are more tests there that can give you some idea of what we're looking for.
> 
> You can find information around acceptance tests here https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html and, obviously, feel free to ask any questions that may pop up :) .

I've attempted to add such a test in the latest commit.

**Comment by koikonom** [comment]
The test was fine, only had a minor change. Going to merge this in v1.17.0 :)

**Pull request merged**
