### PR TITLE
Added a check for invalid ISO file on CD/DVD Drives

### PR DESCRIPTION
**Pull request by jodysimpson**
This is a fix for #413.  

When a VM is created from a template or VM that has an OVF environment,  vSphere will create an ISO and mount it as CD/DVD Drive.  If subsequent VM are created in Terraform after the VM had the ISO loaded,  vSphere will report to Terraform that the CD/Drive is loaded with an ISO of path "[]".  The vSphere provider then tries to access an invalid Datastore field and causes a crash.  

This fix checks to make sure the Datastore is not nil before accessing it, otherwise it skips over it.

### CODE REVIEW

**Comment by vancluever** [comment]
@jodysimpson this seems like a very easy win - thank you for the contribution!

I want to give this a bit more of a run next week just to double check. In the meantime, it would be super helpful if you could get a test added in for this to `resource_vsphere_virtual_machine_test.go`. You can follow [this test](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine_test.go#L650) to see how we manipulate state to make OOB changes to virtual machines to create test cases similar to what you would need to do (eject the ISO from a datastore virtual CDROM device).

Regardless I will loop back on this next week.

Thanks!

**Comment by jodysimpson** [comment]
I am working on the test for this situation,  it’s been difficult trying to recreate a VM that’s causes a crash from scratch.  I can create a problem VM inside vCenter but the vsphere provider either prevents me from creating the problematic situation or does not allow adjustment of the settings.  I am almost there,  it’s just been difficult.

Steps to reproduce:
1.  Create a VM/template with VApp or OVF settings and a CD-Rom that has no media.
2.  Set OVFEnvironmentTransport to ISO.
3. Power on machine.  This loads OVF settings into an ISO and mounts it to the CD-rom.
4. Power off the machine.  This sets the CD-rom media to “[]” with no datastore.
5. Clone this machine to a second VM and have Terraform try to read this new VM.  Can either be a Terraform state import of the already cloned VM or a vsphere_virtual_machine that clones the original VM.

In order to replicate this as a test case,  I am doing the following:
1. Start with the Clone VApp test which copies the CoreOS template.
2. Clone the CoreOS template with an added CD-rom
3.  Once the VM is loaded edit the properties to remove the media from the CD-rom and set the OVFEvironmentTransport to “iso”.  The vsphere provider does not directly allow either of these to be done in HCL.  I am able to create the problematic situation by editing the properties similar to the test case you pointed me to.
4. Power on the VM to have vsphere load the ISO.
5. Power off the VM,  this unloads the ISO and sets it to “[]”
6. Import this VM into a new resource and hopefully crash before my fix.  This is the step I’m stuck on but I should have it fixed soon.  I can’t get the test to crash importing in the test suite.  If I try run a command line state import of the exact same VM it crashes every time.

**Comment by jodysimpson** [comment]
The test case is completed.  vSphere only sets the ISO to [] after a ~6 second timeout after powering down.  I added a 30 second sleep just to be safe.

**Comment by vancluever** [comment]
Hey @jodysimpson, sorry about the delay in getting back to you on this.

Thank you for all your hard work on this, especially on the tests.

Coincidentally, as I think you might have seen in the changelog or other PRs, there has been some work on full support for vApp ISO transports. This work was completed a week or so ago and includes checking for ejected datastore ISO drives.

This work unfortunately supersedes the work here - the test scenario is not really valid anymore as we only allow machines that have vApp ISO transports to have a client CDROM device. A more valid test now would just be with a basic virtual machine with an ejected datastore ISO drive to ensure that the nil check was working properly. Hence I'm just going to close this PR.

Sorry for the inconvenience here and again, thanks for your hard work.

**Pull request closed without merging**
