### PR TITLE
Migrate provider to tf plugin sdk

### PR DESCRIPTION
**Pull request by koikonom**

### CODE REVIEW

**Comment by LorbusChris** [comment]
Looks like this PR broke `provider_test.go`. Over in #948 I had updated the providers used in the test to make tests work.

**Comment by LorbusChris** [comment]
@koikonom @aareet @bill-rich

**Comment by koikonom** [comment]
I'm on it, thanks for noticing!

**Comment by koikonom** [comment]
Created #984 . Sorry for that :)

**Comment by LorbusChris** [comment]
That was quick =) Awesome, thanks!

**Pull request merged**
