### PR TITLE
Migrate to terraform-plugin-sdk

### PR DESCRIPTION
**Pull request by LorbusChris**
In order to make tests pass, this PR also updates the null and random
providers and removes the template provider which can't be used with the
plugin sdk, yet.

See:
terraform-providers/terraform-provider-template#75

### CODE REVIEW

**Comment by LorbusChris** [comment]
Rebased

**Comment by LorbusChris** [comment]
Rebased again. Friendly ping @bill-rich

**Comment by aareet** [comment]
@LorbusChris thank you for the submission, we've got this prioritized and will work on it.

**Comment by CyrusNajmabadi** [comment]
Any progress on this @aareet ?  Thanks!

**Comment by LorbusChris** [comment]
Let me know if there is anything that I can do to speed this up :)

**Comment by stack72** [comment]
ping @aareet :)

**Comment by koikonom** [comment]
Hello,

The provider has now migrated to the tf sdk in PR #982 .

**Comment by LorbusChris** [comment]
Unfortunately it looks like #982 broke the tests (providers used in tests weren't updated to versions that use the plugin-sdk, which causes type mismatches)

**Pull request closed without merging**
