### PR TITLE
r/virtual_machine: API backwards compatability

### PR DESCRIPTION
**Pull request by vancluever**
Ref: #243 

This PR is focusing on addressing compatibility issues, namely with vSphere 5.5.

Thank you very much to @rowanjacobs and @genevievelesperance for their help with testing on older versions!

### CODE REVIEW

**Comment by rowanjacobs** [comment]
The "efiSecureBootEnabled" tag seems to also be a problem.

We're currently running with the `BootOptions` schema property commented out and it's looking promising so far; will update when the test finishes running.

**Comment by vancluever** [comment]
:+1: awesome!

In the meantime I've added a gate for that. Looks like this affects vSphere 6.0 as well as it's only available on 6.5 and higher. I am going to smoke test this on our lab, which is 6.5.

**Comment by vancluever** [comment]
OK, smoke test now works against the latest commit - EFI secure boot gets set properly (also discovered it needed to have `restart_required` flagged to modify so made sure that change is in there).

@rowanjacobs @genevievelesperance would love to know if this works for you on your 5.5 installation!

**Comment by genevievelesperance** [comment]
Hey! We have gotten to a different error but probably something in our own configuration. We will investigate more in the morning:

```
--- FAIL: TestAccResourceVSphereVirtualMachine_Basic (690.39s)
    --- FAIL: TestAccResourceVSphereVirtualMachine_Basic/basic (331.28s)
    	testing.go:503: Step 0 error: Error applying: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: timeout waiting for a routeable interface
    --- FAIL: TestAccResourceVSphereVirtualMachine_Basic/shutdown_OK (333.05s)
    	testing.go:503: Step 0 error: Error applying: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: timeout waiting for a routeable interface
    --- FAIL: TestAccResourceVSphereVirtualMachine_Basic/clone_from_template (26.06s)
    	testing.go:503: Step 0 error: Error applying: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: error sending customization spec: Customization of the guest operating system 'debian7_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.
    	testing.go:563: Error destroying resource! WARNING: Dangling resources
    		may exist. The full state and error is shown below.

    		Error: Check failed: vsphere_virtual_machine.vm not found in state
```

**Comment by vancluever** [comment]
Hey @genevievelesperance yeah a couple of things you want to keep in mind, or some items from our own setup:

* We use Ubuntu templates for cloning and customization testing (might be an issue there with Debian guests specifically)
* For the non-clone tests, you want to make sure that you are booting those on a PXE network that can boot a VM into a full OS environment that has VMware tools installed. We use RancherOS using a custom build of the initrd from my PR here: https://github.com/rancher/os/pull/2138

PS: I'm closing this in favour of #259, which contains all of the commits from #257 and #258 and then a couple of more changes (namely folder support fixes and also a bit of a refactor of the version check for disk sharing just to be consistent). Can you try your tests against that branch, just so that we are all on the same page?

Thanks!

**Pull request closed without merging**
