### PR TITLE
Fix ip mapping from guest to terraform

### LINKED ISSUE #127: vpshere plugin returns the last defined ipadres from the IpStack instead of the first
### Terraform Version
Terraform v0.9.11
terraform-provider-vsphere - master

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files
```hcl
resource "vsphere_virtual_machine" "acceptance-test" {
        name          = "test"
        vcpu          = 1
        memory        = 1024
        datacenter    = "DC0"
        cluster       = "CL0"
        resource_pool = "CL0/RP0"
        network_interface {
                label              = "VM network"
                ipv4_address       = "10.5.8.8"
                ipv4_prefix_length = "24"
                ipv4_gateway       = "10.5.8.1"
		ipv6_address       = "2001:XXXX::8"
		ipv6_prefix_length = "56"
		ipv6_gateway       = "2001:XXXX::1"

        }
        disk { ... }
}
```

### Expected Behavior
no changes in the VM when i run plan/apply for an existing VM with no changes

### Actual Behavior
terraform plan

case where ipv6 returns link-local
~ vsphere_virtual_machine.test
    network_interface.0.ipv6_address:       "fe80::250:56ff:febf:7f29" => "2001:XXXX::8"
    network_interface.0.ipv6_prefix_length: "64" => "56"

case where the last ip is the floating ip between 2 keepalived instances
~ vsphere_virtual_machine.test
    network_interface.0.ipv4_address:       "10.5.8.100" => "10.5.8.8"
    network_interface.0.ipv4_prefix_length: "32" => "24"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### PR DESCRIPTION
**Pull request by mjrider**
- only accept the first ip adres per family instead of the last one
  This is a problem which machines with floating ipaddresses

- for ipv6, reject link-local ipadresses, those are auto-generated

fixes #127

### CODE REVIEW

**Comment by vancluever** [comment]
Thanks @mjrider  - as mentioned will look at this soon :+1:

**Comment by mjrider** [comment]
needs some more work:
- ipv6_gateway: same filtering as for ipv6_address, filter away local scope addresses
- conflicts with #129 ebcause of changes on the same lines

**Comment by vancluever** [comment]
Hey @mjrider - so a weird side-effect here: Using a config like this for network:

```
  network_interface {
    label              = "public"
    ipv4_address       = "172.16.1.150"
    ipv4_prefix_length = 24
    ipv4_gateway       = "172.16.1.1"
  }
```

With an IP address added local to the machine (ie: `ip addr add 172.16.1.151/24 dev eth0`) leads to the following in the state:

```
                            "network_interface.#": "1",
                            "network_interface.0.adapter_type": "",
                            "network_interface.0.ip_address": "",
                            "network_interface.0.ipv4_address": "172.16.1.150",
                            "network_interface.0.ipv4_gateway": "172.16.1.1",
                            "network_interface.0.ipv4_prefix_length": "24",
                            "network_interface.0.ipv6_address": "172.16.1.151",
                            "network_interface.0.ipv6_gateway": "",
                            "network_interface.0.ipv6_prefix_length": "32",
                            "network_interface.0.key": "4000",
                            "network_interface.0.label": "public",
                            "network_interface.0.mac_address": "00:50:56:94:22:d5",
                            "network_interface.0.subnet_mask": "",
```

Note how `172.16.1.151` wound up as the `ipv6_address`.

Looks like this might be because how you are checking for an IPv6 address with net.IP - `To16` will actually convert an IPv4 address to an IPv6 "address":

```
[DEBUG] p.To16 == net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x10, 0x1, 0x97}
```

What you can do, however, is check for `nil` on `To4`. Check https://play.golang.org/p/cKUjXkswjy for an example.

**Comment by mjrider** [comment]
this should fix #16

**Comment by vancluever** [comment]
Hey @mjrider - found another one - this is more just a spurious diff issue, stemming from the normalization of IPv6 addresses:

```
  ~ vsphere_virtual_machine.foo
      network_interface.0.ipv6_address: "fd00::1" => "fd00::0001"
```

Can we some code in to make sure this is skipped in TF (ie: through maybe a [`DiffSuppressFunc`](https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L59) or a [`StateFunc`](https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L111)), whatever one you think might be more appropriate here?

**Comment by mjrider** [comment]
@vancluever i added a  DiffSuppressFunc for ipv4 and ipv6 address and gateway

**Comment by vancluever** [comment]
Hey @mjrider - this fixes the normalization issues on IPv6 addresses - thanks!

Looks like, however, we are still having issues with IPv6 addresses - I added another IPv6 address to the interface (`fd00::2/112`) and am having the same issue now:

```
  ~ vsphere_virtual_machine.foo
      network_interface.0.ipv6_address: "fd00::2" => "fd00::0001"
```

I honestly think that what we will ultimately need to do is separate the guest network info from the network information supplied in Terraform, which is ultimately a configuration specification of sorts (I would have to dig into the API to know 100%). Since re-configuration isn't allowed on regular vSphere anyway, having this set to a `ForceNew` anyway should not necessarily be out of the realm of possibility, with the guest network information being saved to a purely computed hierarchy that does not cause state drift.

This is a longer term thing though and I while IPv6 is important I'd imagine that there are a lot more people with this issue using IPv4, so I'm going to merge this one now. Maybe if you wanted to pick up something, you could see how we could check config to determine if we should even write an IP address to state :)

Thanks for the contribution!

**Pull request merged**
